# Generated by Django 4.0.4 on 2022-04-20 11:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='單位')),
            ],
            options={
                'verbose_name': '單位',
                'verbose_name_plural': '單位',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='名字')),
                ('tel', models.CharField(blank=True, max_length=20, null=True, verbose_name='電話')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='手機')),
                ('email', models.EmailField(blank=True, max_length=70, null=True, verbose_name='信箱')),
                ('note', models.TextField(blank=True, max_length='500', null=True, verbose_name='備註')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipelines.company', verbose_name='單位')),
            ],
            options={
                'verbose_name': '聯絡人',
                'verbose_name_plural': '聯絡人',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateField(default=datetime.date.today, verbose_name='開會日期')),
                ('subject', models.CharField(max_length=40, verbose_name='會議名稱')),
                ('notification_date', models.DateField(default=datetime.date.today, verbose_name='通知單日期')),
                ('notification_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='通知單文號')),
                ('agenda', models.TextField(blank=True, null=True, verbose_name='議題')),
                ('minutes', models.TextField(blank=True, max_length=1000, null=True, verbose_name='會議記錄')),
                ('issue_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='會議記錄文號')),
                ('issue_date', models.DateField(default=datetime.date.today, verbose_name='發文日期')),
                ('minutes_file', models.FileField(blank=True, null=True, upload_to='media/file/', verbose_name='檔案上傳')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/photo/', verbose_name='照片上傳')),
                ('company', models.ManyToManyField(to='pipelines.company', verbose_name='與會單位')),
                ('contact_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_person', to='pipelines.contact', verbose_name='聯絡人')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='host', to='pipelines.contact', verbose_name='主持人')),
            ],
            options={
                'verbose_name': '行事曆',
                'verbose_name_plural': '行事曆',
            },
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10, null=True, verbose_name='道路名稱')),
            ],
            options={
                'verbose_name': '道路清單',
                'verbose_name_plural': '道路清單',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, max_length=1000, verbose_name='內容')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='預計完成日期')),
                ('company', models.ManyToManyField(to='pipelines.company', verbose_name='相關單位')),
                ('road', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipelines.road', verbose_name='影響道路')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipelines.meeting', verbose_name='名稱')),
            ],
            options={
                'verbose_name': '待辦清單',
                'verbose_name_plural': '待辦清單',
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='road',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipelines.road', verbose_name='地點'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='部門')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipelines.company', verbose_name='單位')),
            ],
            options={
                'verbose_name': '部門',
                'verbose_name_plural': '部門',
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipelines.department', verbose_name='部門'),
        ),
    ]
