# Generated by Django 4.0.4 on 2022-04-20 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='company',
        ),
    ]
