# Generated by Django 4.0.4 on 2022-04-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0007_meeting_keynote_file_meeting_other_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='summary',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='摘要'),
        ),
    ]
