# Generated by Django 4.0.4 on 2022-04-22 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0008_meeting_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='issue_date',
            field=models.DateField(default=datetime.date.today, verbose_name='會議記錄發文日期'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='road',
        ),
        migrations.AddField(
            model_name='task',
            name='road',
            field=models.ManyToManyField(to='pipelines.road', verbose_name='影響道路'),
        ),
    ]
