# Generated by Django 4.0.4 on 2022-04-25 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0009_alter_meeting_issue_date_remove_task_road_task_road'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='標題')),
                ('link', models.CharField(max_length=255, verbose_name='連結')),
                ('type', models.CharField(choices=[('w', 'website'), ('n', 'news')], default='n', help_text='選擇連結種類', max_length=1)),
            ],
            options={
                'verbose_name': '網站連結',
                'verbose_name_plural': '網站連結',
            },
        ),
    ]
