# Generated by Django 4.0.4 on 2022-04-25 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0010_websitelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitelink',
            name='summary',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='摘要'),
        ),
        migrations.AlterField(
            model_name='websitelink',
            name='type',
            field=models.CharField(choices=[('w', '友站連結'), ('n', '新聞媒體')], default='n', help_text='選擇網站種類', max_length=1, verbose_name='網站種類'),
        ),
    ]
