# Generated by Django 4.0.4 on 2022-04-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0011_websitelink_summary_alter_websitelink_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('number',), 'verbose_name': '單位', 'verbose_name_plural': 'E.單位'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': '聯絡人', 'verbose_name_plural': 'G.聯絡人'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': '部門', 'verbose_name_plural': 'F.部門'},
        ),
        migrations.AlterModelOptions(
            name='meeting',
            options={'verbose_name': '行事曆', 'verbose_name_plural': 'A.行事曆'},
        ),
        migrations.AlterModelOptions(
            name='road',
            options={'verbose_name': '道路清單', 'verbose_name_plural': 'C.道路清單'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': '待辦清單', 'verbose_name_plural': 'B.待辦清單'},
        ),
        migrations.AlterModelOptions(
            name='websitelink',
            options={'verbose_name': '網站連結', 'verbose_name_plural': 'D.網站連結'},
        ),
        migrations.AddField(
            model_name='company',
            name='number',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='分類編號'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='單位'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='部門'),
        ),
        migrations.AlterField(
            model_name='road',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='道路名稱'),
        ),
        migrations.AlterField(
            model_name='websitelink',
            name='link',
            field=models.CharField(help_text='需包含https://', max_length=255, verbose_name='連結'),
        ),
        migrations.AlterField(
            model_name='websitelink',
            name='type',
            field=models.CharField(choices=[('w', '相關網站'), ('n', '新聞媒體')], default='n', help_text='選擇網站種類', max_length=1, verbose_name='網站種類'),
        ),
    ]
