# Generated by Django 4.0.4 on 2022-04-27 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0012_alter_company_options_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='road',
            name='actual_completion',
            field=models.DateField(default=datetime.date.today, verbose_name='實際完工日'),
        ),
        migrations.AddField(
            model_name='road',
            name='actual_construction',
            field=models.DateField(default=datetime.date.today, verbose_name='實際施工日'),
        ),
        migrations.AddField(
            model_name='road',
            name='coordinate',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='座標'),
        ),
        migrations.AddField(
            model_name='road',
            name='estimated_completion',
            field=models.DateField(default=datetime.date.today, verbose_name='預計完工日'),
        ),
        migrations.AddField(
            model_name='road',
            name='estimated_construction',
            field=models.DateField(default=datetime.date.today, verbose_name='預計施工日'),
        ),
        migrations.AddField(
            model_name='road',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='位置'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='單位名稱'),
        ),
    ]
