# Generated by Django 4.0.4 on 2022-04-27 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipelines', '0013_road_actual_completion_road_actual_construction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='專案項目')),
            ],
            options={
                'verbose_name': '專案項目',
                'verbose_name_plural': 'C.專案項目',
            },
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ('number',), 'verbose_name': 'F通訊錄', 'verbose_name_plural': 'F通訊錄'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': '聯絡人', 'verbose_name_plural': '聯絡人'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': '部門', 'verbose_name_plural': '部門'},
        ),
        migrations.AlterModelOptions(
            name='road',
            options={'verbose_name': '道路清單', 'verbose_name_plural': 'D.道路清單'},
        ),
        migrations.AlterModelOptions(
            name='websitelink',
            options={'verbose_name': '網站連結', 'verbose_name_plural': 'E.網站連結'},
        ),
        migrations.AddField(
            model_name='meeting',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipelines.project', verbose_name='專案項目'),
        ),
    ]
